### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by ido1990** [K2IE/ASL-Build#2]
Hi,
Thank you for the script, I upgraded my Debian to Buster on my laptop and my Allstar got broken.
It seems like the script doesn't work on my system.
[This is my log](https://pastebin.com/6er3XCtK)
Do you have any idea why it doesn't work?
Thanks!

**Comment by K2IE** [comment]
The script has been tested on fresh installs of Buster.  It has not been tested in a situation where an existing Debian Jessie has been upgraded to Buster.

**Comment by ido1990** [comment]
Ok, I'll try on a fresh installation.
